[package]
name = "arplay"
version = "0.1.0"
authors = ["rdspot <rdspot@arpnetwork.org>"]

[dependencies]
ffmpeg-sys = "3.4.1"
sdl2 = { version = "0.31.0", features = ["unsafe_textures"] }
bytes = "0.4.8"
